/*
 * ============================================================
 *  ESPController.cpp
 *  Part of ESPController Library by Shamil K, Vismaya P
 *  https://github.com/shamilslk/ESPController
 *  Version : 2.0.0
 * ============================================================
 */


// ============================================================
//  ESPController.cpp
//  Do NOT edit this file.  All configuration goes in your .ino.
// ============================================================
#include "ESPController.h"

// ════════════════════════════════════════════════════════════
//  SINGLETON
// ════════════════════════════════════════════════════════════
ESPController& ESPController::instance() {
  static ESPController i;
  return i;
}
ESPController::ESPController() {}

// ════════════════════════════════════════════════════════════
//  CONFIGURATION SETTERS
// ════════════════════════════════════════════════════════════
void ESPController::setWiFi(const char* s, const char* p, ControllerWiFiMode m)
  { _ssid = s; _pass = p; _wifiMode = m; }

void ESPController::setMDNS(const char* h)
  { _mdnsOn = true; _mdnsHost = h; }

void ESPController::setMotorAPins(uint8_t a, uint8_t b)
  { _aIn1 = a; _aIn2 = b; _motorsEnabled = true; }

void ESPController::setMotorBPins(uint8_t a, uint8_t b)
  { _bIn1 = a; _bIn2 = b; _motorsEnabled = true; }

void ESPController::setWatchdogTimeout(unsigned long ms) { _watchdogMs = ms; }
void ESPController::setMaxSpeed(uint8_t s)               { _maxSpeed = s; }

void ESPController::setMotorTrim(MotorSide side, int8_t t) {
  t = constrain(t, -100, 100);
  if (side == MotorSide::LEFT) _trimA = t; else _trimB = t;
}

void ESPController::setAcceleration(uint8_t step, uint16_t ms)
  { _accelStep = step; _accelTickMs = ms; }

// ════════════════════════════════════════════════════════════
//  CALLBACK REGISTRATION
// ════════════════════════════════════════════════════════════
void ESPController::onUp   (ButtonCallback c) { _cbUp    = c; }
void ESPController::onDown (ButtonCallback c) { _cbDown  = c; }
void ESPController::onLeft (ButtonCallback c) { _cbLeft  = c; }
void ESPController::onRight(ButtonCallback c) { _cbRight = c; }
void ESPController::onStop (ButtonCallback c) { _cbStop  = c; }

void ESPController::onJoystick   (JoystickCallback    c) { _cbJoy    = c; }
void ESPController::onJoystickRaw(JoystickRawCallback c) { _cbJoyRaw = c; }

void ESPController::onControllerConnected   (EventCallback c) { _cbCtrlConn    = c; }
void ESPController::onControllerDisconnected(EventCallback c) { _cbCtrlDisconn = c; }

// Camera callbacks — only compiled for ESP32-CAM
#ifdef BOARD_ESP32CAM
void ESPController::onCameraConnected   (EventCallback c) { _cbCamConn    = c; }
void ESPController::onCameraDisconnected(EventCallback c) { _cbCamDisconn = c; }
#endif

void ESPController::onLowBattery(uint8_t pin, uint32_t mv, EventCallback c) {
  _batPin = pin; _batThreshMv = mv; _cbLowBat = c;
  _batEnabled = true;
  pinMode(pin, INPUT);
}

// ════════════════════════════════════════════════════════════
//  MOTOR WRITE — board-specific PWM vs digitalWrite
//
//  ESP32 / ESP32-S3 / ESP32-CAM  →  ledcWrite   (8-bit, 0-255)
//  ESP8266 with USE_PWM_MOTORS   →  analogWrite (10-bit, 0-1023)
//  Any board without USE_PWM_MOTORS → digitalWrite HIGH/LOW
// ════════════════════════════════════════════════════════════
void ESPController::_writeMotor(uint8_t p1, uint8_t p2, int speed, int8_t trim) {
  // Apply trim then clamp to allowed range
  speed = speed + (speed * trim / 100);
  speed = constrain(speed, -(int)_maxSpeed, (int)_maxSpeed);

#ifdef USE_PWM_MOTORS
  // ── PWM path ────────────────────────────────────────────
  #ifdef BOARD_ESP8266
    // ESP8266 analogWrite: 10-bit (0-1023)
    if (speed > 0) {
      analogWrite(p1, map(speed,  0, 255, 0, 1023));
      analogWrite(p2, 0);
    } else if (speed < 0) {
      analogWrite(p1, 0);
      analogWrite(p2, map(-speed, 0, 255, 0, 1023));
    } else {
      analogWrite(p1, 0);
      analogWrite(p2, 0);
    }
  #else
    // ESP32 / ESP32-S3 / ESP32-CAM: LEDC 8-bit (0-255)
    if (speed > 0) {
      ledcWrite(p1,  speed);
      ledcWrite(p2,  0);
    } else if (speed < 0) {
      ledcWrite(p1,  0);
      ledcWrite(p2, -speed);
    } else {
      ledcWrite(p1, 0);
      ledcWrite(p2, 0);
    }
  #endif // BOARD_ESP8266

#else
  // ── Digital path (no PWM) ───────────────────────────────
  if (speed > 0) {
    digitalWrite(p1, HIGH);
    digitalWrite(p2, LOW);
  } else if (speed < 0) {
    digitalWrite(p1, LOW);
    digitalWrite(p2, HIGH);
  } else {
    digitalWrite(p1, LOW);
    digitalWrite(p2, LOW);
  }
#endif // USE_PWM_MOTORS
}

// ════════════════════════════════════════════════════════════
//  MOTOR PUBLIC HELPERS
// ════════════════════════════════════════════════════════════
void ESPController::setMotorA(int speed) {
  if (!_motorsEnabled) return;
  _targetA = constrain(speed, -255, 255);
  if (_accelStep >= 255) {
    _currentA = _targetA;
    _writeMotor(_aIn1, _aIn2, _currentA, _trimA);
  }
  _lastCmdTime = millis();
}

void ESPController::setMotorB(int speed) {
  if (!_motorsEnabled) return;
  _targetB = constrain(speed, -255, 255);
  if (_accelStep >= 255) {
    _currentB = _targetB;
    _writeMotor(_bIn1, _bIn2, _currentB, _trimB);
  }
  _lastCmdTime = millis();
}

void ESPController::stopMotors()   { setMotorA(0); setMotorB(0); }

void ESPController::emergencyStop() {
  _targetA = _targetB = _currentA = _currentB = 0;
  if (_motorsEnabled) {
    _writeMotor(_aIn1, _aIn2, 0, 0);
    _writeMotor(_bIn1, _bIn2, 0, 0);
  }
#ifdef HAS_FLASH_LED
  _setFlash(0);
#endif
  _lastCmdTime = millis();
}

// ════════════════════════════════════════════════════════════
//  CONNECTIVITY / TELEMETRY
// ════════════════════════════════════════════════════════════
int     ESPController::getRSSI()        { return WiFi.RSSI(); }
uint8_t ESPController::getRSSIQuality() {
  int r = getRSSI();
  if (r >= -50)  return 100;
  if (r <= -100) return 0;
  return (uint8_t)(2 * (r + 100));
}

String ESPController::getStatusJSON() {
  String ip = (_wifiMode == ControllerWiFiMode::AP)
                ? WiFi.softAPIP().toString()
                : WiFi.localIP().toString();

  String json = "{\"ip\":\""        + ip
    + "\",\"rssi\":"                + String(getRSSI())
    + ",\"rssi_quality\":"          + String(getRSSIQuality())
    + ",\"ctrl_clients\":"          + String(_wsCtrl ? _wsCtrl->count() : 0)
    // --- ESP32-CAM extras ---
#ifdef BOARD_ESP32CAM
    + ",\"cam_clients\":"           + String(_wsCamera ? _wsCamera->count() : 0)
    + ",\"fps\":"                   + String(_frameInterval > 0 ? 1000 / _frameInterval : 0)
#endif
    // --- Flash LED brightness (any board with HAS_FLASH_LED) ---
#ifdef HAS_FLASH_LED
    + ",\"flash\":"                 + String(_flashBrightness)
#endif
    + ",\"max_speed\":"             + String(_maxSpeed)
    + "}";
  return json;
}

// ════════════════════════════════════════════════════════════
//  FLASH LED
//  Compiled only when HAS_FLASH_LED is defined.
//  ESP8266      → analogWrite (10-bit mapped)
//  ESP32 family → ledcWrite  (8-bit, channel attached in begin())
// ════════════════════════════════════════════════════════════
#ifdef HAS_FLASH_LED
void ESPController::_setFlash(int b) {
  _flashBrightness = constrain(b, 0, 255);
#ifdef BOARD_ESP8266
  analogWrite(FLASH_LED_PIN, map(_flashBrightness, 0, 255, 0, 1023));
#else
  ledcWrite(FLASH_LED_PIN, _flashBrightness);
#endif
}
#endif // HAS_FLASH_LED

// ════════════════════════════════════════════════════════════
//  STATUS LED
//  Compiled only when HAS_STATUS_LED is defined.
//  Uses plain digitalWrite — works on all boards.
// ════════════════════════════════════════════════════════════
#ifdef HAS_STATUS_LED
void ESPController::_blinkStatus(int n, int ms) {
  for (int i = 0; i < n; i++) {
    digitalWrite(STATUS_LED_PIN, HIGH); delay(ms);
    digitalWrite(STATUS_LED_PIN, LOW);  delay(ms);
  }
}
#endif // HAS_STATUS_LED

// ════════════════════════════════════════════════════════════
//  CAMERA  — ESP32-CAM only
//  Nothing in this block compiles on ESP32 / ESP32-S3 / ESP8266.
// ════════════════════════════════════════════════════════════
#ifdef BOARD_ESP32CAM
bool ESPController::_initCamera() {
  camera_config_t c = {};
  c.ledc_channel  = LEDC_CHANNEL_0;
  c.ledc_timer    = LEDC_TIMER_0;
  c.pin_d0        = CAM_PIN_Y2;    c.pin_d1   = CAM_PIN_Y3;
  c.pin_d2        = CAM_PIN_Y4;    c.pin_d3   = CAM_PIN_Y5;
  c.pin_d4        = CAM_PIN_Y6;    c.pin_d5   = CAM_PIN_Y7;
  c.pin_d6        = CAM_PIN_Y8;    c.pin_d7   = CAM_PIN_Y9;
  c.pin_xclk      = CAM_PIN_XCLK;  c.pin_pclk  = CAM_PIN_PCLK;
  c.pin_vsync     = CAM_PIN_VSYNC; c.pin_href  = CAM_PIN_HREF;
  c.pin_sscb_sda  = CAM_PIN_SIOD;  c.pin_sscb_scl = CAM_PIN_SIOC;
  c.pin_pwdn      = CAM_PIN_PWDN;  c.pin_reset = CAM_PIN_RESET;
  c.xclk_freq_hz  = 20000000;
  c.pixel_format  = PIXFORMAT_JPEG;
  c.frame_size    = FRAMESIZE_QVGA;
  c.jpeg_quality  = 12;
  c.fb_count      = 2;

  esp_err_t err = esp_camera_init(&c);
  if (err != ESP_OK) {
    Serial.printf("[CAM] Init failed: 0x%x\n", err);
    return false;
  }
  _sensor = esp_camera_sensor_get();
  Serial.println("[CAM] OK");
  return true;
}

void ESPController::_sendFrame() {
  if (!_wsCamera || _wsCamera->count() == 0) return;
  camera_fb_t* fb = esp_camera_fb_get();
  if (!fb) return;
  _wsCamera->binaryAll(fb->buf, fb->len);
  esp_camera_fb_return(fb);
}
#endif // BOARD_ESP32CAM

// ════════════════════════════════════════════════════════════
//  BATTERY MONITOR
//  ADC resolution: ESP8266 = 10-bit (0-1023), ESP32 family = 12-bit (0-4095)
//  Vref assumed 3.3 V for all boards.
// ════════════════════════════════════════════════════════════
void ESPController::_checkBattery() {
  if (!_batEnabled || _batAlertFired) return;
  unsigned long now = millis();
  if (now - _lastBatCheck < 5000) return;
  _lastBatCheck = now;

#ifdef BOARD_ESP8266
  uint32_t mv = (analogRead(_batPin) * 3300UL) / 1023UL;
#else
  // ESP32 / ESP32-S3 / ESP32-CAM: 12-bit ADC
  uint32_t mv = (analogRead(_batPin) * 3300UL) / 4095UL;
#endif

  if (mv <= _batThreshMv) {
    _batAlertFired = true;
    if (_cbLowBat) _cbLowBat();
  }
}

// ════════════════════════════════════════════════════════════
//  BUTTON AUTO-RELEASE
//  If no repeated press arrives within BUTTON_RELEASE_MS,
//  the library synthesises a release event (LOW callback).
// ════════════════════════════════════════════════════════════
void ESPController::_checkButtonReleases() {
  unsigned long now = millis();
  if (_upActive    && now - _upLastMs    > BUTTON_RELEASE_MS) { _upActive    = false; if (_cbUp)    _cbUp(LOW);    }
  if (_downActive  && now - _downLastMs  > BUTTON_RELEASE_MS) { _downActive  = false; if (_cbDown)  _cbDown(LOW);  }
  if (_leftActive  && now - _leftLastMs  > BUTTON_RELEASE_MS) { _leftActive  = false; if (_cbLeft)  _cbLeft(LOW);  }
  if (_rightActive && now - _rightLastMs > BUTTON_RELEASE_MS) { _rightActive = false; if (_cbRight) _cbRight(LOW); }
}

// ════════════════════════════════════════════════════════════
//  COMMAND PARSER
//  Called from WebSocket event handler and HTTP GET routes.
// ════════════════════════════════════════════════════════════
void ESPController::_handleCommand(const String& msg) {
  Serial.printf("[CMD] %s\n", msg.c_str());
  _lastCmdTime = millis();
  unsigned long now = millis();

  // ── D-pad / stop ───────────────────────────────────────
  if (msg == "up") {
    _upActive = true; _upLastMs = now;
    if (_cbUp) _cbUp(HIGH);
    return;
  }
  if (msg == "down") {
    _downActive = true; _downLastMs = now;
    if (_cbDown) _cbDown(HIGH);
    return;
  }
  if (msg == "left") {
    _leftActive = true; _leftLastMs = now;
    if (_cbLeft) _cbLeft(HIGH);
    return;
  }
  if (msg == "right") {
    _rightActive = true; _rightLastMs = now;
    if (_cbRight) _cbRight(HIGH);
    return;
  }
  if (msg == "stop") {
    _upActive = _downActive = _leftActive = _rightActive = false;
    if (_cbStop) _cbStop(HIGH);
    return;
  }

  // ── Joystick  "joy:x,y"  x/y in -1.0 … +1.0 ──────────
  if (msg.startsWith("joy:")) {
    String xy = msg.substring(4);
    int comma = xy.indexOf(',');
    if (comma > 0) {
      float fx = xy.substring(0, comma).toFloat();
      float fy = xy.substring(comma + 1).toFloat();
      if (_cbJoyRaw) _cbJoyRaw(fx, fy);
      if (_cbJoy)    _cbJoy((int)(fx * 255), (int)(fy * 255));
    }
    return;
  }

  // ── Flash LED  "flash:<0-255>"  ─────────────────────────
  // Available on any board that has HAS_FLASH_LED defined.
#ifdef HAS_FLASH_LED
  if (msg.startsWith("flash:")) {
    _setFlash(msg.substring(6).toInt());
    return;
  }
#endif

  // ── RGB status LED used as flash substitute "flash:<0-255>" ──
  // App only sends a single brightness value; we feed it into R, G, B
  // equally so 255 = white, 0 = off (e.g. ESP32-S3 with no real flash LED).
#ifdef HAS_RGB_STATUS_LED
  if (msg.startsWith("flash:")) {
    int v = constrain(msg.substring(6).toInt(), 0, 255);
    _rgbStatus.setPixelColor(0, _rgbStatus.Color(v, v, v));
    _rgbStatus.show();
    return;
  }
#endif

  // ── Camera controls  "cam:key=value"  ───────────────────
  // Compiled only for ESP32-CAM. Commands: fps, quality, res.
#ifdef BOARD_ESP32CAM
  if (msg.startsWith("cam:")) {
    if (!_sensor) return;
    String kv  = msg.substring(4);
    int    eq   = kv.indexOf('=');
    if (eq < 0) return;
    String key = kv.substring(0, eq);
    String val = kv.substring(eq + 1);

    if (key == "fps") {
      _frameInterval = 1000 / constrain(val.toInt(), 5, 30);
    } else if (key == "quality") {
      _sensor->set_quality(_sensor, constrain(val.toInt(), 5, 30));
    } else if (key == "res") {
      if      (val == "QVGA") _sensor->set_framesize(_sensor, FRAMESIZE_QVGA);
      else if (val == "VGA")  _sensor->set_framesize(_sensor, FRAMESIZE_VGA);
      else if (val == "SVGA") _sensor->set_framesize(_sensor, FRAMESIZE_SVGA);
    }
    return;
  }
#endif // BOARD_ESP32CAM
}

// ════════════════════════════════════════════════════════════
//  WEBSOCKET EVENT HANDLERS
// ════════════════════════════════════════════════════════════

// ── /control WebSocket — all boards ────────────────────────
void ESPController::_onCtrlEvent(AsyncWebSocket* srv,
    AsyncWebSocketClient* client, AwsEventType type,
    void* arg, uint8_t* data, size_t len) {
  ESPController& c = instance();

  if (type == WS_EVT_CONNECT) {
    Serial.println("[CTRL] App connected");
    if (c._cbCtrlConn) c._cbCtrlConn();

  } else if (type == WS_EVT_DISCONNECT) {
    Serial.println("[CTRL] App disconnected — emergency stop");
    c.emergencyStop();
    c._upActive = c._downActive = c._leftActive = c._rightActive = false;
    if (c._cbCtrlDisconn) c._cbCtrlDisconn();

  } else if (type == WS_EVT_DATA) {
    AwsFrameInfo* info = (AwsFrameInfo*)arg;
    if (info->opcode == WS_TEXT) {
      String msg = "";
      msg.reserve(len);
      for (size_t i = 0; i < len; i++) msg += (char)data[i];
      msg.trim();
      c._handleCommand(msg);
    }
  }
}

// ── /camera WebSocket — ESP32-CAM only ─────────────────────
#ifdef BOARD_ESP32CAM
void ESPController::_onCamEvent(AsyncWebSocket* srv,
    AsyncWebSocketClient* client, AwsEventType type,
    void* arg, uint8_t* data, size_t len) {
  ESPController& c = instance();

  if (type == WS_EVT_CONNECT) {
    Serial.println("[CAM] Viewer connected");
    if (c._cbCamConn) c._cbCamConn();
  } else if (type == WS_EVT_DISCONNECT) {
    Serial.println("[CAM] Viewer disconnected");
    if (c._cbCamDisconn) c._cbCamDisconn();
  }
}
#endif // BOARD_ESP32CAM

// ════════════════════════════════════════════════════════════
//  BEGIN
// ════════════════════════════════════════════════════════════
bool ESPController::begin() {
  Serial.println("[CTRL] ESPController starting...");

  // ── Status LED ──────────────────────────────────────────
#ifdef HAS_STATUS_LED
  pinMode(STATUS_LED_PIN, OUTPUT);
  digitalWrite(STATUS_LED_PIN, LOW);
#endif

  // ── RGB Status LED ──────────────────────────────────────
#ifdef HAS_RGB_STATUS_LED
  _rgbStatus.begin();
  _rgbStatus.setPixelColor(0, _rgbStatus.Color(0, 0, 0));
  _rgbStatus.show();
#endif

  // ── Flash LED init ──────────────────────────────────────
  // ESP8266: plain analogWrite.  ESP32 family: LEDC attach first.
#ifdef HAS_FLASH_LED
  #ifdef BOARD_ESP8266
    pinMode(FLASH_LED_PIN, OUTPUT);
    analogWrite(FLASH_LED_PIN, 0);
  #else
    // One LEDC channel for the flash pin
    ledcAttach(FLASH_LED_PIN, 5000, 8);
    _setFlash(0);
    // Brief test flash so you know it initialised
    _setFlash(180); delay(200); _setFlash(0);
  #endif
#endif

  // ── Motor pin init ──────────────────────────────────────
  if (_motorsEnabled) {
#ifdef USE_PWM_MOTORS
  #ifdef BOARD_ESP8266
    // ESP8266: set as OUTPUT then zero via analogWrite
    pinMode(_aIn1, OUTPUT); pinMode(_aIn2, OUTPUT);
    pinMode(_bIn1, OUTPUT); pinMode(_bIn2, OUTPUT);
    analogWrite(_aIn1, 0);  analogWrite(_aIn2, 0);
    analogWrite(_bIn1, 0);  analogWrite(_bIn2, 0);
  #else
    // ESP32 / ESP32-S3 / ESP32-CAM: attach LEDC channels
    ledcAttach(_aIn1, MOTOR_LEDC_FREQ, MOTOR_LEDC_RES);
    ledcAttach(_aIn2, MOTOR_LEDC_FREQ, MOTOR_LEDC_RES);
    ledcAttach(_bIn1, MOTOR_LEDC_FREQ, MOTOR_LEDC_RES);
    ledcAttach(_bIn2, MOTOR_LEDC_FREQ, MOTOR_LEDC_RES);
    ledcWrite(_aIn1, 0); ledcWrite(_aIn2, 0);
    ledcWrite(_bIn1, 0); ledcWrite(_bIn2, 0);
  #endif
#else
    // Digital-only (no PWM)
    pinMode(_aIn1, OUTPUT); pinMode(_aIn2, OUTPUT);
    pinMode(_bIn1, OUTPUT); pinMode(_bIn2, OUTPUT);
    digitalWrite(_aIn1, LOW); digitalWrite(_aIn2, LOW);
    digitalWrite(_bIn1, LOW); digitalWrite(_bIn2, LOW);
#endif
    Serial.println("[MOTORS] Ready");
  }

  // ── WiFi ────────────────────────────────────────────────
  if (_wifiMode == ControllerWiFiMode::AP) {
    WiFi.softAP(_ssid, _pass);
    Serial.print("[WIFI] AP IP: ");
    Serial.println(WiFi.softAPIP());
  } else {
    WiFi.begin(_ssid, _pass);
    Serial.print("[WIFI] Connecting to router");
    unsigned long t = millis();
    while (WiFi.status() != WL_CONNECTED && millis() - t < 15000) {
      delay(500); Serial.print(".");
    }
    if (WiFi.status() == WL_CONNECTED) {
      Serial.println();
      Serial.print("[WIFI] IP: "); Serial.println(WiFi.localIP());
    } else {
      Serial.println("\n[WIFI] Failed — falling back to AP");
      WiFi.softAP(_ssid, _pass);
      Serial.print("[WIFI] AP IP: "); Serial.println(WiFi.softAPIP());
    }
  }

  // ── mDNS ────────────────────────────────────────────────
  // ESP8266: MDNS.begin() needs the IP passed explicitly.
  // ESP32 family: IP auto-detected.
  if (_mdnsOn) {
#ifdef BOARD_ESP8266
    if (MDNS.begin(_mdnsHost, WiFi.localIP())) {
#else
    if (MDNS.begin(_mdnsHost)) {
#endif
      MDNS.addService("http", "tcp", 80);
      Serial.printf("[mDNS] http://%s.local\n", _mdnsHost);
    }
  }

  Serial.printf("[CTRL] Free heap: %d bytes\n", ESP.getFreeHeap());

  // ── Camera init (ESP32-CAM only) ─────────────────────────
  // On other boards this entire block is removed by the preprocessor.
#ifdef BOARD_ESP32CAM
  if (!_initCamera()) {
    Serial.println("[CAM] FAILED — halting");
#ifdef HAS_STATUS_LED
    while (true) { _blinkStatus(1, 100); delay(100); }  // rapid blink = camera fault
#else
    while (true) { delay(1000); }
#endif
    return false;
  }
#endif

  // ── Web server + WebSockets ──────────────────────────────
  _server = new AsyncWebServer(80);
  _wsCtrl = new AsyncWebSocket("/control");
  _wsCtrl->onEvent(_onCtrlEvent);
  _server->addHandler(_wsCtrl);

  // /camera WebSocket — compiled only for ESP32-CAM
#ifdef BOARD_ESP32CAM
  _wsCamera = new AsyncWebSocket("/camera");
  _wsCamera->onEvent(_onCamEvent);
  _server->addHandler(_wsCamera);
#endif

  // ── HTTP routes — all boards ─────────────────────────────
  _server->on("/up",    HTTP_GET, [](AsyncWebServerRequest* r)
    { instance()._handleCommand("up");    r->send(200, "text/plain", "OK"); });
  _server->on("/down",  HTTP_GET, [](AsyncWebServerRequest* r)
    { instance()._handleCommand("down");  r->send(200, "text/plain", "OK"); });
  _server->on("/left",  HTTP_GET, [](AsyncWebServerRequest* r)
    { instance()._handleCommand("left");  r->send(200, "text/plain", "OK"); });
  _server->on("/right", HTTP_GET, [](AsyncWebServerRequest* r)
    { instance()._handleCommand("right"); r->send(200, "text/plain", "OK"); });
  _server->on("/stop",  HTTP_GET, [](AsyncWebServerRequest* r)
    { instance()._handleCommand("stop");  r->send(200, "text/plain", "OK"); });

  _server->on("/joystick", HTTP_GET, [](AsyncWebServerRequest* req) {
    if (req->hasArg("x") && req->hasArg("y")) {
      instance()._handleCommand("joy:" + req->arg("x") + "," + req->arg("y"));
      req->send(200, "text/plain", "OK");
    } else {
      req->send(400, "text/plain", "Missing x or y");
    }
  });

  // /cam settings route — ESP32-CAM only
#ifdef BOARD_ESP32CAM
  _server->on("/cam", HTTP_GET, [](AsyncWebServerRequest* req) {
    ESPController& c = instance();
    if (!c._sensor) { req->send(500, "text/plain", "No camera"); return; }
    if (req->hasArg("res"))     c._handleCommand("cam:res="     + req->arg("res"));
    if (req->hasArg("fps"))     c._handleCommand("cam:fps="     + req->arg("fps"));
    if (req->hasArg("quality")) c._handleCommand("cam:quality=" + req->arg("quality"));
#ifdef HAS_FLASH_LED
    if (req->hasArg("flash"))   c._setFlash(constrain(req->arg("flash").toInt(), 0, 255));
#endif
    req->send(200, "text/plain", "OK");
  });
#endif

  _server->on("/status", HTTP_GET, [](AsyncWebServerRequest* req) {
    req->send(200, "application/json", instance().getStatusJSON());
  });

  _server->begin();
  Serial.println("[HTTP] Server ready on port 80");

#ifdef HAS_STATUS_LED
  _blinkStatus(2, 300);   // 2 blinks = started successfully
#endif

  _lastCmdTime = millis();
  Serial.println("[CTRL] Ready");
  return true;
}

// ════════════════════════════════════════════════════════════
//  UPDATE  — call every loop()
// ════════════════════════════════════════════════════════════
void ESPController::update() {
  unsigned long now = millis();

  // Auto-release buttons that haven't repeated
  _checkButtonReleases();

  // Motor watchdog — zero targets if controller goes silent
  if (_watchdogMs > 0 && _motorsEnabled && now - _lastCmdTime > _watchdogMs) {
    _targetA = _targetB = 0;
  }

  // Soft acceleration ramp
  if (_motorsEnabled && now - _lastAccelTick >= _accelTickMs) {
    _lastAccelTick = now;
    auto step = [](int cur, int tgt, int s) -> int {
      if (cur < tgt) return min(cur + s, tgt);
      if (cur > tgt) return max(cur - s, tgt);
      return cur;
    };
    int nA = step(_currentA, _targetA, _accelStep);
    int nB = step(_currentB, _targetB, _accelStep);
    if (nA != _currentA) { _currentA = nA; _writeMotor(_aIn1, _aIn2, _currentA, _trimA); }
    if (nB != _currentB) { _currentB = nB; _writeMotor(_bIn1, _bIn2, _currentB, _trimB); }
  }

  // Camera frame pump — ESP32-CAM only
#ifdef BOARD_ESP32CAM
  if (_wsCamera && _wsCamera->count() > 0 && now - _lastFrameTime >= _frameInterval) {
    _sendFrame();
    _lastFrameTime = now;
  }
  if (_wsCamera) _wsCamera->cleanupClients();
#endif

  // WebSocket housekeeping — all boards
  if (_wsCtrl) _wsCtrl->cleanupClients();

  // Battery ADC check
  _checkBattery();

  // RSSI broadcast every 3 s to connected app
  if (_wsCtrl && _wsCtrl->count() > 0 && now - _lastRssiTime >= 3000) {
    _lastRssiTime = now;
    _wsCtrl->textAll("rssi:" + String(getRSSI()) + ",q:" + String(getRSSIQuality()));
  }

  // ESP8266 requires MDNS.update() in every loop
#ifdef BOARD_ESP8266
  if (_mdnsOn) MDNS.update();
#endif
}
